config/routes.rb
Rails.application.routes.draw do
  resources :encounter_character_refs
  resources :character_pull_role_refs
  resources :ranks
  resources :sigils
  resources :affixes
  resources :prefixes
  resources :cclasses
  resources :roles
  root 'squads#index'

  resources :encounters
  resources :pull_roles
  resources :pulls
  resources :squads
  resources :characters
  resources :players

end

app/models/affix.rb
class Affix < ActiveRecord::Base
end

app/models/cclass.rb
class Cclass < ActiveRecord::Base
end

app/models/character.rb
class Character < ActiveRecord::Base
    belongs_to :player
    has_many :squads
end

app/models/encounter.rb
class Encounter < ActiveRecord::Base
    has_many :pulls
    has_many :characters
end

app/models/player.rb
class Player < ActiveRecord::Base
    belongs_to :squad
    has_many :characters
end

app/models/prefix.rb
class Prefix < ActiveRecord::Base
end

app/models/pull.rb
class Pull < ActiveRecord::Base
    belongs_to :encounter
end

app/models/pull_role.rb
class PullRole < ActiveRecord::Base
    belongs_to :pull
end

app/models/rank.rb
class Rank < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/sigil.rb
class Sigil < ActiveRecord::Base
end

app/models/squad.rb
class Squad < ActiveRecord::Base
    has_many :characters
    has_many :pulls
end

app/controllers/squads_controller.rb
class SquadsController < ApplicationController
  before_action :set_squad, only: [:show, :edit, :update, :destroy]

  # GET /squads
  # GET /squads.json
  def index
    @squads = Squad.all
  end

  # GET /squads/1
  # GET /squads/1.json
  def show
  end

  # GET /squads/new
  def new
    @squad = Squad.new
  end

  # GET /squads/1/edit
  def edit
  end

  # POST /squads
  # POST /squads.json
  def create
    @squad = Squad.new(squad_params)

    respond_to do |format|
      if @squad.save
        format.html { redirect_to @squad, notice: 'Squad was successfully created.' }
        format.json { render :show, status: :created, location: @squad }
      else
        format.html { render :new }
        format.json { render json: @squad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /squads/1
  # PATCH/PUT /squads/1.json
  def update
    respond_to do |format|
      if @squad.update(squad_params)
        format.html { redirect_to @squad, notice: 'Squad was successfully updated.' }
        format.json { render :show, status: :ok, location: @squad }
      else
        format.html { render :edit }
        format.json { render json: @squad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /squads/1
  # DELETE /squads/1.json
  def destroy
    @squad.destroy
    respond_to do |format|
      format.html { redirect_to squads_url, notice: 'Squad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_squad
      @squad = Squad.find(params[:id])
      @characters = Character.where(:squad_id == @squad.id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def squad_params
      params.require(:squad).permit(:string)
    end
end

app/helpers/affixes_helper.rb
module AffixesHelper
end

app/helpers/cclasses_helper.rb
module CclassesHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/prefixes_helper.rb
module PrefixesHelper
end

app/helpers/pulls_helper.rb
module PullsHelper
end

app/helpers/ranks_helper.rb
module RanksHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sigils_helper.rb
module SigilsHelper
end

app/helpers/squads_helper.rb
module SquadsHelper
end

app/views/squads/_form.html.erb
<%= form_for(@squad) do |f| %>
  <% if @squad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@squad.errors.count, "error") %> prohibited this squad from being saved:</h2>

      <ul>
      <% @squad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/squads/edit.html.erb
<h1>Editing Squad</h1>

<%= render 'form' %>

<%= link_to 'Show', @squad %> |
<%= link_to 'Back', squads_path %>

app/views/squads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Squads</h1>

<table border= "1">
  <thead>
    <tr>
      <th>Squad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @squads.each do |squad| %>
      <tr>
        <td><%= squad.name %></td>
        <td><%= link_to 'Show', squad %></td>
        <td><%= link_to 'Edit', edit_squad_path(squad) %></td>
        <td><%= link_to 'Destroy', squad, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Squad', new_squad_path %>

app/views/squads/new.html.erb
<h1>New Squad</h1>

<%= render 'form' %>

<%= link_to 'Back', squads_path %>

app/views/squads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @squad.name %>
  
  
<h1>Listing Characters</h1>

    <table border = "1">
      <thead>
        <tr>
          <td>Name</td>
          <td>Role</td>
          <td>Class</td>
          <td>Prefix</td>
          <td>Affix</td>
          <td>Sigil 1</td>
          <td>Sigil 2</td>
          <td>Sigil 3</td>
          <td>Sigil 4</td>
          <td>Toughness</td>
          <td>Armor Class</td>
          <th colspan="3"></th>
        </tr>
    </thead>
  
    <tbody>
        <% @characters.each do |c| %>
        <tr>
          <td><%= c.name %></td>
           <td><%=Role.find(c.role).name %></td>
           <td><%=Cclass.find(c.cclass).name %></td>
           <td><%=Prefix.find(c.prefix).name %></td>
           <td><%=Affix.find(c.affix).name %></td>
           <td><%=Sigil.find(c.sigil_1).name %></td>
           <td><%=Sigil.find(c.sigil_2).name %></td>
           <td><%=Sigil.find(c.sigil_3).name %></td>
           <td><%=Sigil.find(c.sigil_4).name %></td>
           <td><%=c.toughness %></td>
           <td><%=c.ac %></td>

          <td><%= link_to 'Show', c %></td>
          <td><%= link_to 'Edit', edit_character_path(c) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
      
</p>

<%= link_to 'Edit', edit_squad_path(@squad) %> |
<%= link_to 'Back', squad_path %> 