config/routes.rb
Rails.application.routes.draw do
  resources :encounter_character_refs
  resources :character_pull_role_refs
  resources :ranks
  resources :sigils
  resources :affixes
  resources :prefixes
  resources :cclasses
  resources :roles
  root 'squads#index'

  resources :encounters
  resources :pull_roles
  resources :pulls
  resources :squads
  resources :characters
  resources :players

end

app/models/affix.rb
class Affix < ActiveRecord::Base
end

app/models/cclass.rb
class Cclass < ActiveRecord::Base
end

app/models/character.rb
class Character < ActiveRecord::Base
    belongs_to :player
    has_many :squads
end

app/models/encounter.rb
class Encounter < ActiveRecord::Base
    has_many :pulls
    has_many :characters
end

app/models/player.rb
class Player < ActiveRecord::Base
    belongs_to :squad
    has_many :characters
end

app/models/prefix.rb
class Prefix < ActiveRecord::Base
end

app/models/pull.rb
class Pull < ActiveRecord::Base
    belongs_to :encounter
end

app/models/pull_role.rb
class PullRole < ActiveRecord::Base
    belongs_to :pull
end

app/models/rank.rb
class Rank < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/sigil.rb
class Sigil < ActiveRecord::Base
end

app/models/squad.rb
class Squad < ActiveRecord::Base
    has_many :characters
    has_many :pulls
end

app/controllers/sigils_controller.rb
class SigilsController < ApplicationController
  before_action :set_sigil, only: [:show, :edit, :update, :destroy]

  # GET /sigils
  # GET /sigils.json
  def index
    @sigils = Sigil.all
  end

  # GET /sigils/1
  # GET /sigils/1.json
  def show
  end

  # GET /sigils/new
  def new
    @sigil = Sigil.new
  end

  # GET /sigils/1/edit
  def edit
  end

  # POST /sigils
  # POST /sigils.json
  def create
    @sigil = Sigil.new(sigil_params)

    respond_to do |format|
      if @sigil.save
        format.html { redirect_to @sigil, notice: 'Sigil was successfully created.' }
        format.json { render :show, status: :created, location: @sigil }
      else
        format.html { render :new }
        format.json { render json: @sigil.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sigils/1
  # PATCH/PUT /sigils/1.json
  def update
    respond_to do |format|
      if @sigil.update(sigil_params)
        format.html { redirect_to @sigil, notice: 'Sigil was successfully updated.' }
        format.json { render :show, status: :ok, location: @sigil }
      else
        format.html { render :edit }
        format.json { render json: @sigil.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sigils/1
  # DELETE /sigils/1.json
  def destroy
    @sigil.destroy
    respond_to do |format|
      format.html { redirect_to sigils_url, notice: 'Sigil was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sigil
      @sigil = Sigil.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sigil_params
      params.require(:sigil).permit(:name, :description)
    end
end

app/helpers/affixes_helper.rb
module AffixesHelper
end

app/helpers/cclasses_helper.rb
module CclassesHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/prefixes_helper.rb
module PrefixesHelper
end

app/helpers/pulls_helper.rb
module PullsHelper
end

app/helpers/ranks_helper.rb
module RanksHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sigils_helper.rb
module SigilsHelper
end

app/helpers/squads_helper.rb
module SquadsHelper
end

app/views/sigils/_form.html.erb
<%= form_for(@sigil) do |f| %>
  <% if @sigil.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sigil.errors.count, "error") %> prohibited this sigil from being saved:</h2>

      <ul>
      <% @sigil.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sigils/edit.html.erb
<h1>Editing Sigil</h1>

<%= render 'form' %>

<%= link_to 'Show', @sigil %> |
<%= link_to 'Back', sigils_path %>

app/views/sigils/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sigils</h1>

<table border= "1">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sigils.each do |sigil| %>
      <tr>
        <td><%= sigil.name %></td>
        <td><%= sigil.description %></td>
        <td><%= link_to 'Show', sigil %></td>
        <td><%= link_to 'Edit', edit_sigil_path(sigil) %></td>
        <td><%= link_to 'Destroy', sigil, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sigil', new_sigil_path %>

app/views/sigils/new.html.erb
<h1>New Sigil</h1>

<%= render 'form' %>

<%= link_to 'Back', sigils_path %>

app/views/sigils/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sigil.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @sigil.description %>
</p>

<%= link_to 'Edit', edit_sigil_path(@sigil) %> |
<%= link_to 'Back', sigils_path %>