config/routes.rb
Rails.application.routes.draw do
  resources :encounter_character_refs
  resources :character_pull_role_refs
  resources :ranks
  resources :sigils
  resources :affixes
  resources :prefixes
  resources :cclasses
  resources :roles
  root 'squads#index'

  resources :encounters
  resources :pull_roles
  resources :pulls
  resources :squads
  resources :characters
  resources :players

end

app/models/affix.rb
class Affix < ActiveRecord::Base
end

app/models/cclass.rb
class Cclass < ActiveRecord::Base
end

app/models/character.rb
class Character < ActiveRecord::Base
    belongs_to :player
    has_many :squads
end

app/models/encounter.rb
class Encounter < ActiveRecord::Base
    has_many :pulls
    has_many :characters
end

app/models/player.rb
class Player < ActiveRecord::Base
    belongs_to :squad
    has_many :characters
end

app/models/prefix.rb
class Prefix < ActiveRecord::Base
end

app/models/pull.rb
class Pull < ActiveRecord::Base
    belongs_to :encounter
end

app/models/pull_role.rb
class PullRole < ActiveRecord::Base
    belongs_to :pull
end

app/models/rank.rb
class Rank < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/sigil.rb
class Sigil < ActiveRecord::Base
end

app/models/squad.rb
class Squad < ActiveRecord::Base
    has_many :characters
    has_many :pulls
end

app/controllers/affixes_controller.rb
class AffixesController < ApplicationController
  before_action :set_affix, only: [:show, :edit, :update, :destroy]

  # GET /affixes
  # GET /affixes.json
  def index
    @affixes = Affix.all
  end

  # GET /affixes/1
  # GET /affixes/1.json
  def show
  end

  # GET /affixes/new
  def new
    @affix = Affix.new
  end

  # GET /affixes/1/edit
  def edit
  end

  # POST /affixes
  # POST /affixes.json
  def create
    @affix = Affix.new(affix_params)

    respond_to do |format|
      if @affix.save
        format.html { redirect_to @affix, notice: 'Affix was successfully created.' }
        format.json { render :show, status: :created, location: @affix }
      else
        format.html { render :new }
        format.json { render json: @affix.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /affixes/1
  # PATCH/PUT /affixes/1.json
  def update
    respond_to do |format|
      if @affix.update(affix_params)
        format.html { redirect_to @affix, notice: 'Affix was successfully updated.' }
        format.json { render :show, status: :ok, location: @affix }
      else
        format.html { render :edit }
        format.json { render json: @affix.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /affixes/1
  # DELETE /affixes/1.json
  def destroy
    @affix.destroy
    respond_to do |format|
      format.html { redirect_to affixes_url, notice: 'Affix was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_affix
      @affix = Affix.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def affix_params
      params.require(:affix).permit(:name, :description)
    end
end

app/helpers/affixes_helper.rb
module AffixesHelper
end

app/helpers/cclasses_helper.rb
module CclassesHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/prefixes_helper.rb
module PrefixesHelper
end

app/helpers/pulls_helper.rb
module PullsHelper
end

app/helpers/ranks_helper.rb
module RanksHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sigils_helper.rb
module SigilsHelper
end

app/helpers/squads_helper.rb
module SquadsHelper
end

app/views/affixes/_form.html.erb
<%= form_for(@affix) do |f| %>
  <% if @affix.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@affix.errors.count, "error") %> prohibited this affix from being saved:</h2>

      <ul>
      <% @affix.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/affixes/edit.html.erb
<h1>Editing Affix</h1>

<%= render 'form' %>

<%= link_to 'Show', @affix %> |
<%= link_to 'Back', affixes_path %>

app/views/affixes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Affixes</h1>

<table border= "1">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @affixes.each do |affix| %>
      <tr>
        <td><%= affix.name %></td>
        <td><%= affix.description %></td>
        <td><%= link_to 'Show', affix %></td>
        <td><%= link_to 'Edit', edit_affix_path(affix) %></td>
        <td><%= link_to 'Destroy', affix, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Affix', new_affix_path %>

app/views/affixes/new.html.erb
<h1>New Affix</h1>

<%= render 'form' %>

<%= link_to 'Back', affixes_path %>

app/views/affixes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @affix.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @affix.description %>
</p>

<%= link_to 'Edit', edit_affix_path(@affix) %> |
<%= link_to 'Back', affixes_path %>