config/routes.rb
Rails.application.routes.draw do
  resources :encounter_character_refs
  resources :character_pull_role_refs
  resources :ranks
  resources :sigils
  resources :affixes
  resources :prefixes
  resources :cclasses
  resources :roles
  root 'squads#index'

  resources :encounters
  resources :pull_roles
  resources :pulls
  resources :squads
  resources :characters
  resources :players

end

app/models/affix.rb
class Affix < ActiveRecord::Base
end

app/models/cclass.rb
class Cclass < ActiveRecord::Base
end

app/models/character.rb
class Character < ActiveRecord::Base
    belongs_to :player
    has_many :squads
end

app/models/character_pull_role_ref.rb
class CharacterPullRoleRef < ActiveRecord::Base
end

app/models/encounter.rb
class Encounter < ActiveRecord::Base
    has_many :pulls
    has_many :characters
end

app/models/player.rb
class Player < ActiveRecord::Base
    belongs_to :squad
    has_many :characters
end

app/models/prefix.rb
class Prefix < ActiveRecord::Base
end

app/models/pull.rb
class Pull < ActiveRecord::Base
    belongs_to :encounter
end

app/models/pull_role.rb
class PullRole < ActiveRecord::Base
    belongs_to :pull
end

app/models/rank.rb
class Rank < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/sigil.rb
class Sigil < ActiveRecord::Base
end

app/models/squad.rb
class Squad < ActiveRecord::Base
    has_many :characters
    has_many :pulls
end

app/controllers/character_pull_role_refs_controller.rb
class CharacterPullRoleRefsController < ApplicationController
  before_action :set_character_pull_role_ref, only: [:show, :edit, :update, :destroy]

  # GET /character_pull_role_refs
  # GET /character_pull_role_refs.json
  def index
    @character_pull_role_refs = CharacterPullRoleRef.all
  end

  # GET /character_pull_role_refs/1
  # GET /character_pull_role_refs/1.json
  def show
  end

  # GET /character_pull_role_refs/new
  def new
    @character_pull_role_ref = CharacterPullRoleRef.new
  end

  # GET /character_pull_role_refs/1/edit
  def edit
  end

  # POST /character_pull_role_refs
  # POST /character_pull_role_refs.json
  def create
    @character_pull_role_ref = CharacterPullRoleRef.new(character_pull_role_ref_params)

    respond_to do |format|
      if @character_pull_role_ref.save
        format.html { redirect_to @character_pull_role_ref, notice: 'Character pull role ref was successfully created.' }
        format.json { render :show, status: :created, location: @character_pull_role_ref }
      else
        format.html { render :new }
        format.json { render json: @character_pull_role_ref.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /character_pull_role_refs/1
  # PATCH/PUT /character_pull_role_refs/1.json
  def update
    respond_to do |format|
      if @character_pull_role_ref.update(character_pull_role_ref_params)
        format.html { redirect_to @character_pull_role_ref, notice: 'Character pull role ref was successfully updated.' }
        format.json { render :show, status: :ok, location: @character_pull_role_ref }
      else
        format.html { render :edit }
        format.json { render json: @character_pull_role_ref.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /character_pull_role_refs/1
  # DELETE /character_pull_role_refs/1.json
  def destroy
    @character_pull_role_ref.destroy
    respond_to do |format|
      format.html { redirect_to character_pull_role_refs_url, notice: 'Character pull role ref was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character_pull_role_ref
      @character_pull_role_ref = CharacterPullRoleRef.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def character_pull_role_ref_params
      params.require(:character_pull_role_ref).permit(:pull_role_id, :character_id)
    end
end

app/helpers/affixes_helper.rb
module AffixesHelper
end

app/helpers/cclasses_helper.rb
module CclassesHelper
end

app/helpers/character_pull_role_refs_helper.rb
module CharacterPullRoleRefsHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/pulls_helper.rb
module PullsHelper
end

app/helpers/ranks_helper.rb
module RanksHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sigils_helper.rb
module SigilsHelper
end

app/helpers/squads_helper.rb
module SquadsHelper
end

app/views/character_pull_role_refs/_form.html.erb
<%= simple_form_for @character_pull_role_ref do |f| %>
    <% if @character_pull_role_ref.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@character_pull_role_ref.errors.count, "error") %> prohibited this character_pull_role_ref from being saved:</h2>
  
        <ul>
        <% @character_pull_role_ref.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    
  <p>
  <strong>Encounter:</strong>
  <%= Encounter.find(PullRole.find(@character_pull_role_ref.pull_role_id).encounter_id).name %>
  </p>
  
  <%= f.input :character_id,:collection => Character.all,:label_method => :name,:value_method => :id,:label => "Character Name" ,:include_blank => true %>
  <%= f.input :pull_role_id,:collection => PullRole.all,:label_method => :name,:value_method => :id,:label => "Pull Role" ,:include_blank => true %>
  <%= f.button :submit %>
<% end %>

app/views/character_pull_role_refs/edit.html.erb
<h1>Editing Character Pull Role Ref</h1>

<%= render 'form' %>

<%= link_to 'Show', @character_pull_role_ref %> |
<%= link_to 'Back', character_pull_role_refs_path %>

app/views/character_pull_role_refs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Character Pull Role Refs</h1>

<table border= "1">
  <thead>
    <tr>
      <th>Pull role</th>
      <th>Character</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @character_pull_role_refs.each do |character_pull_role_ref| %>
      <tr>
        <td><b><%= Encounter.find(PullRole.find(character_pull_role_ref.pull_role_id).encounter_id).name %></b></td>
        <td><%= PullRole.find(character_pull_role_ref.pull_role_id).name %></td>
        <td><%= Character.find(character_pull_role_ref.character_id).name %></td>
        <td><%= link_to 'Show', character_pull_role_ref %></td>
        <td><%= link_to 'Edit', edit_character_pull_role_ref_path(character_pull_role_ref) %></td>
        <td><%= link_to 'Destroy', character_pull_role_ref, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Character pull role ref', new_character_pull_role_ref_path %>

app/views/character_pull_role_refs/new.html.erb
<h1>New Character Pull Role Ref</h1>

<%= render 'form' %>

<%= link_to 'Back', character_pull_role_refs_path %>

app/views/character_pull_role_refs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Encounter:</strong>
  <%= Encounter.find(PullRole.find(@character_pull_role_ref.pull_role_id).encounter_id).name %>
</p>


<p>
  <strong>Pull role:</strong>
  <%= PullRole.find(@character_pull_role_ref.pull_role_id).name %>
</p>

<p>
  <strong>Character:</strong>
  <%= Character.find(@character_pull_role_ref.character_id).name %>
</p>

<%= link_to 'Edit', edit_character_pull_role_ref_path(@character_pull_role_ref) %> |
<%= link_to 'Back', character_pull_role_refs_path %>